### ISSUE TITLE
Ruby Capstone Project Setup - Kanbaan board

### ISSUE THREAD

**Issue by gak92** [Owusu-Desmond/catalog-of-my-things-app#27]
Team Members (3): 
@Mesi21 (Team Member # 01), @Owusu-Desmond (Team Member # 02), @gak92 (Team Member # 03) 

Link of the project:
[https://github.com/Owusu-Desmond/catalog-of-my-things-app/projects/1](https://github.com/Owusu-Desmond/catalog-of-my-things-app/projects/1)

**Comment by m05e5** [comment]
Hi @gak92, @Mesi21, and @Owusu-Desmond 

Good job so far. I really like what you did!
There are some issues that you still need to work on to go to the next project but you are almost there!
![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)


## Highlights


## Required Changes ♻️
* You really did a great job but there are some features you need to improve
 
- [ ] great job with your Kanban board. As mentioned in the requirements, members of a team are supposed to have equal(or approximately equal) contributions to the project. Still, in your kanban board, a student has 8 more Pts than the others which is not very good planning. please kindly reconsider the task sharing so that every student participates equally
 
_I'm sure you can do it just keep it up_

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_@m05e5_

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by gak92** [comment]
@m05e5,
Thanks for the review.
We changed the card so each team member will get equal time.

**Comment by m05e5** [comment]
@gak92 Nice. you can ask for another review

**Comment by gemmen29** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 💯 
- Descriptive info ✔️ 
- Tasks distributed equally ✔️ 

![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)

## Optional suggestions

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
